### PR TITLE
Implement generic `assert_impl` macro

### PR DESCRIPTION
**Pull request by Nadrieril**
After squinting for a while at the wrapper trick for `assert_impl_any`, it turns out it generalizes quite well. I implemented a generic `assert_impl` macro with type-level booleans that covers most of the cases where we want to check for a type implementing a set of traits.
Examples:
```rust
assert_impl!(Cell<u32>: Send && !Sync);
assert_impl!(u32: (Into<u16>) || (Into<u64>));
assert_impl!(for(T) Rc<T>: Clone);
assert_impl!(for(T: Copy) T: Clone);
```
The error messages are also quite nice:
```
error[E0308]: mismatched types
  --> tests/trait_impl.rs:66:1
   |
66 | assert_impl!(for(T) T: Clone);
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `static_assertions::True`, found struct `static_assertions::False`
   |
   = note: expected type `static_assertions::True`
              found type `static_assertions::False`
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

### CODE REVIEW

**Comment by Nadrieril** [comment]
There are a few limitations to the syntax due to macro shenanigans. Maybe we should make a proc_macro instead.

**Comment by Nadrieril** [comment]
This subsumes #27.

**Comment by Nadrieril** [comment]
Since the `True` and `False` structs are local to the macro, I believe that this is safe against external blanket traits

**Comment by Nadrieril** [comment]
I just saw that https://github.com/nvzqz/static-assertions-rs/issues/26 had a similar idea. I could use const booleans too actually, as long as I can recover pretty error messages

**Comment by nvzqz** [comment]
This is awesome!! One of my plans for 2.0 was to consolidate the `assert_impl*!` family of macros into a single one that uses `!` for "not", `|` for "any", and `&` for "all". I haven't had the time to sit down and attempt it, so thank you very much for putting in the work!

> After squinting for a while at the wrapper trick for `assert_impl_any`

I can only imagine you've been squinting for quite some time. I'm very impressed by you being able to do this. I'll read through the implementation when I have more time this weekend to make sense of your [`tt` munching](https://danielkeep.github.io/tlborm/book/pat-incremental-tt-munchers.html).

**Comment by Nadrieril** [comment]
> could you extract the bits that emit True and False to the assert_impl*! family of macros?

I'm not sure what you mean :/

> I'd like to improve those error messages

I am in the process of using the newly defined `type_level_bool::{True, False}` types in `assert_impl` to get better errors :)

**Comment by nvzqz** [comment]
So the error message here shows:

```
expected struct `_::True`, found struct `_::False`
```

I was saying I'd like that for the old macros.

But it seems that you've redefined the other macros to use this new macro instead. So I imagine you'd get that for free.

**Comment by Nadrieril** [comment]
Rebased on master and now we got the pretty errors

**Comment by nvzqz** [comment]
Thanks! I'll definitely try to check this out soon.

Your `True` and `False` type stuff got me to create [`typebool`](https://github.com/nvzqz/typebool).

**Comment by Nadrieril** [comment]
We probably don't need that much structure on `True` and `False`. I'd rather use const booleans if we can instead, I just haven't quite figured out how because the deref trick can't be used to generate a const value

**Comment by Nadrieril** [comment]
Ugh I hit an ICE https://github.com/rust-lang/rust/issues/62708 when trying to use const bool instead of type-level bools :(

**Comment by Nadrieril** [comment]
Ok, so now it's easy to get a const type-level boolean testing whether a type implements a particular bunch of traits. It's also easy to get a const bool from that. But because of https://github.com/rust-lang/rust/issues/62708, we can't use `const_assert` on that boolean and remove the intermediate type-level bools :(

**Comment by nvzqz** [comment]
Sorry I haven't gotten back to you on this. Life got in the way. I'll review this soon, I promise!

**Comment by nvzqz** [comment]
Hey @Nadrieril thanks again for this PR! ❤️

I finally got around to looking through it and I'm happy with the implementation. Apologies for it taking so long to review. A new version will be released soon with this macro!

**Comment by nvzqz** [comment]
@Nadrieril I rewrote the macro and fixed all of the issues with it! And I decided to put it into its own library at https://github.com/nvzqz/impls. I credited you as co-author in the `README.md`, in the `LICENSE-MIT` file, and in the `Cargo.toml` file. I posted it [on Twitter](https://twitter.com/NikolaiVazquez/status/1211736934445408256) and people seem to like it. Thanks again!

**Comment by Nadrieril** [comment]
That's great ! You seem to have dropped support for generics though ?

**Comment by wycats** [comment]
@nvzqz I was surprised to see the missing support for `for(...)` generics as well. I see that the code is still in `assert_impl`, but `assert_impl` seems not to be exposed.

**Comment by wycats** [comment]
Upon further investigation, it looks like the issue is that the commits after November 3, 2019 were never released to crates.io.

**Comment by TTWNO** [comment]
@nvzqz Can you please release the latest changes on crates.io? I realize the functionality of this crate is quite stable, but this feature would help me a lot.

Happy to help if needed.

**Pull request merged**
